#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative './rake/vcpkg_utils'
require_relative './rake/dependencies'
require_relative './rake/documentation'

desc 'Install reqired libraries'
task :install_libs do
  install_dependencies
end

desc 'Show the list of required libraries'
task :list_libs do
  list_dependencies
end

desc 'Bootstraping vcpkg'
task :vcpkg_bootstrap do
  bootstrap_vcpkg
end

desc 'Execute vcpkg and pass arguments to it'
task :vcpkg do
  exec_vcpkg
end

desc 'Generate documentation via doxygen'
task :gen_docs do
  gen_docs
end

desc 'Delete generated documentation'
task :clear_docs do
  clear_docs
end

desc 'Get index.html\'s path of generated documentation as URL format'
task :get_docs_path do
  get_docs_path
end
